language: golang
sudo: required
services:
  - docker


before_install:
  - docker-compose build

script:
  - docker-compose run --rm web go test

after_success:
  - docker login -u $DOCKER_ID -p DOCKER_PASSWORD
  - docker-compose push