language: golang
sudo: required
services:
  - docker

env:
  global:
    - SHA: $(git rev-parse HEAD)


before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker-compose build

script:
  - echo "running tests"
  - docker-compose run --rm web go test

after_success:
  - docker-compose push