language: golang
sudo: required
services:
  - docker

env:
  global:
    - SHA: $(git rev-parse HEAD)


before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker-compose build
  - docker tag miladkhodabandehloo/go-web:latest    miladkhodabandehloo/go-web:$SHA
  - docker tag miladkhodabandehloo/go-nginx:latest    miladkhodabandehloo/go-nginx:$SHA


script:
  - echo "running tests"
  - docker-compose run --rm web go test

after_success:
  - docker-compose push