version: "3"

services:

  db_server:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    env_file:
      - my.env


  web:
    build: .
    volumes:
    - "./static/:/go/src/go-web/static/"
    - "/go/src/go-web/static/info/"
    restart: "on-failure"
    ports:
    - "8000"
    depends_on:
      - "db_server"
    image: "miladkhodabandehloo/go-web"
    env_file:
      - my.env
    version_tag:
      extends: build
      image: "miladkhodabandehloo/go-web:{$GIT_SHA}"


  nginx:
    build:
      context: .
      dockerfile: nginxDockerfile
    image: "miladkhodabandehloo/go-nginx"
    env_file:
      - my.env
    version_tag:
      extends: build
      image: "miladkhodabandehloo/go-nginx:{GIT_SHA}"

    ports:
    - "80:80"
    depends_on:
      - "web"
