version: "3"

services:

  db_server:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "my-secret"
      POSTGRES_DB: "app"

  web:
    build: .
    volumes:
    - "./static/:/go/src/go-web/static/"
    - "/go/src/go-web/static/info/"
    restart: "on-failure"
    ports:
    - "8000"
    depends_on:
      - "db_server"
    image: "miladkhodabandehloo/go-web"

  nginx:
    build:
      context: .
      dockerfile: nginxDockerfile
    image: "miladkhodabandehloo/go-nginx"

    ports:
    - "80:80"
    depends_on:
      - "web"
