apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      component:  postgres

  template:
    metadata:
      labels:
        component:  postgres
    spec:
      volumes:
        - name: postgres-sotrage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name:  db-server
          image:  postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              value: app